FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update && apt-get install -yq --no-install-recommends \
    curl \
    minicom \
    screen \
    wget \
    build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ./build.sh %%RESIN_MACHINE_NAME%% '2.12.5+rev2.prod' example_module

CMD ./run.sh
